CREATE DATABASE IF NOT EXISTS Stack;
USE Stack;

CREATE TABLE IF NOT EXISTS User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    ResetCode VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Companies (
    CompanyID INT AUTO_INCREMENT PRIMARY KEY,
    CompanyName VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS User_Company (
    UserID INT,
    CompanyID INT,
    PRIMARY KEY (UserID, CompanyID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Project (
    ProjectID INT AUTO_INCREMENT PRIMARY KEY,
    ProjectName VARCHAR(255) NOT NULL,
    ProjectIcon VARCHAR(255),
    Location VARCHAR(255),
    CompanyID INT,
    FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Preferences (
    PreferenceID INT AUTO_INCREMENT PRIMARY KEY,
    FontSize INT NOT NULL DEFAULT 12,
    ColorMode ENUM('light', 'dark') NOT NULL DEFAULT 'light',
    UserID INT UNIQUE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ChatHistory (
    ChatID INT AUTO_INCREMENT PRIMARY KEY,
    Text TEXT NOT NULL,
    Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ProjectID INT,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Media (
    MediaID INT AUTO_INCREMENT PRIMARY KEY,
    Filename VARCHAR(255) NOT NULL,
    Type ENUM('audio', 'video', 'image', 'js', 'css', 'html') NOT NULL,
    Location VARCHAR(255) NOT NULL,
    ProjectID INT,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE
);
