CREATE DATABASE IF NOT EXISTS Stack;
USE Stack;

CREATE TABLE IF NOT EXISTS User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    ResetCode VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS Company (
    CompanyID INT AUTO_INCREMENT PRIMARY KEY,
    CompanyName VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Project (
    ProjectID INT AUTO_INCREMENT PRIMARY KEY,
    ProjectName VARCHAR(255) NOT NULL,
    URI VARCHAR(255) NOT NULL

);


CREATE TABLE IF NOT EXISTS User_Company (
    UserID INT,
    CompanyID INT,
    PRIMARY KEY (UserID, CompanyID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Company_Project (
    CompanyID INT,
    ProjectID INT,
    PRIMARY KEY (CompanyID, ProjectID),
    FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID) ON DELETE CASCADE,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Preference (
    PreferenceID INT AUTO_INCREMENT PRIMARY KEY,
    FontSize INT NOT NULL DEFAULT 12,
    ColorMode ENUM('light', 'dark') NOT NULL DEFAULT 'light',
    UserID INT UNIQUE,
    FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Chat (
    ChatID INT AUTO_INCREMENT PRIMARY KEY,
    Text TEXT NOT NULL,
    Author VARCHAR(255) NOT NULL,
    Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ProjectID INT,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Media (
    MediaID INT AUTO_INCREMENT PRIMARY KEY,
    Filename VARCHAR(255) NOT NULL,
    Type ENUM('audio', 'video', 'image', 'js', 'css', 'html') NOT NULL,
    URI VARCHAR(255) NOT NULL,
    ProjectID INT,
    FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE CASCADE
);
